name: Tems
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_map: ^3.1.0
  latlng: ^0.2.0
  latlong2: ^0.8.1
  http: ^0.13.6
  get: ^4.6.6
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  multi_dropdown: ^2.0.0
  fl_chart: ^0.66.2
  google_fonts: ^4.0.4
  oktoast: ^3.4.0
  pointycastle: ^3.9.0
  encrypt: ^5.0.3
  csv: ^6.0.0
  share: ^2.0.4
  pdf: ^3.10.8
  avatar_glow: ^3.0.1
  syncfusion_flutter_charts: ^25.2.4
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/image/
    - assets/
